### ISSUE TITLE
The ghcup command in the README does not work with ghcup 0.1.19.0

### ISSUE THREAD

**Issue by Kleidukos** [tomsmeding/play-haskell#20]
`ghcup install ghc -p x86_64-deb10-linux 8.10.7` returns an error:

> Invalid argument `8.10.7'

**Comment by tomsmeding** [comment]
Hm, it seems ghcup doesn't take the `-p` flag anymore. This was necessary for a couple of GHC versions (that were built with Fedora 33, [it seems](https://gitlab.haskell.org/ghc/ghc/-/issues/22268)) if the host OS was Arch, because the Fedora bindists it downloaded then were not compatible with the Ubuntu sandbox OS.

The only thing I see in the ghcup user guide now is [this](https://www.haskell.org/ghcup/guide/#overriding-distro-detection), which is I guess a possibility but more heavyweight than I would like. @hasufell Am I missing something, or was there a particular reason to remove the `-p` flag to `ghcup install ghc`?

**Comment by hasufell** [comment]
P flag still exists, but comes after `ghcup` directly: `ghcup -p <triple> install ghc`.
